# Generated by Django 5.2 on 2026-04-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='render_func',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
