# Generated by Django 5.2 on 2026-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_render_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='render_func',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
