# Generated by Django 5.2 on 2026-04-13 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='unique_answer_per_participant_question'),
        ),
    ]
