# Generated by Django 5.2 on 2026-04-14 09:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_answer_participant_participant_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('sex', models.BooleanField()),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(150)])),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_type',
        ),
        migrations.AddField(
            model_name='question',
            name='ecg_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.ecgrecord'),
        ),
    ]
