# Generated by Django 5.2 on 2026-04-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_ecgrecord_remove_question_choice_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='render_func',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
