# Define named group of servers called django that Nginx can proxy requests to
# upstream lets you add multiple servers for load balancing
upstream django {
    server web:8080; # use Docker internal network
}

# Define virtual server that listens on port 80
server {
    listen 80;

    # Serve static files directly from the /static/ directory inside
    # the Nginx container (where the docker shared static_volume is
    # mounted). These files are served directly without touching
    # Django (much faster)
    location /static/ {
        # alias replaces the location prefix (/static/) with the path (/static/)
        alias /static/;

        # root /; couldn't be used because root appends the full URI to the path
        # it would end up being /static/static/...
    }

    # Pass everything else to Django
    location / {
        proxy_pass http://django; # django is the name of the upstream block the request
        # is forwared to. 

        proxy_set_header Host $host; # pass original host header to django, otherwise django
        # would see web:8080 as host instead of localhost (or domain.ex), and would make
        # django's allowed_hosts configuration fail

        proxy_set_header X-Real-IP $remote_addr; # see user's IP instead of Nginx internal IP

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # list all of the proxies
        # the request passed through

        proxy_set_header X-Forwarded-Proto $scheme; # tells django whether original request is
        # http or https


        ### During development disable cache:
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}